dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
language: csharp
dotnet: 6.0.1
solution: ./Ccs.Ppg.NotificationService.sln
install:
  - dotnet restore ./Ccs.Ppg.NotificationService.sln
mono: none
script:
  - dotnet build --configuration Release ./Ccs.Ppg.NotificationService.sln
  - pwd
deploy:
  - provider: cloudfoundry
    username: $username
    password: $password
    api: $api
    organization: $organisation
    space: $TRAVIS_BRANCH
    manifest: /home/travis/build/Crown-Commercial-Service/ccs-ppg-notification-api/manifest.yml
    skip-cleanup: true
    edge: true
    on:
      branch: $TRAVIS_BRANCH
before_deploy:
- sh app.sh