name: Trufflehog Monthly Deep Scan


on:
  push:
    branches:
    - "**"
      
jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Trufflehog-latest
        run: |
          pip3 install trufflehog
      - name: Run Trufflehog Monthly Deep Scan
        
        #Configure the correct git url of the repo to be scanned
        run: |
          trufflehog https://github.com/rahulgandhijayabalan-bc/ccs-ppg-notification-api.git --regex --entropy=TRUE
  
