name: Trufflehog PR Scan

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

on:
  pull_request:
    branches:
      - "**"
      
jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trufflehog
        run: |
          pip3 install trufflehog

      - name: Run Trufflehog Scan
        id: trufflehog
        run: |
          trufflehog https://github.com/rahulgandhijayabalan-bc/ccs-ppg-notification-api.git --regex --entropy=TRUE

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
