# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Unit Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}/Ccs.Ppg.NotificationService.sln
      - name: Build
        run: dotnet build ${{ github.workspace }}/Ccs.Ppg.NotificationService.sln --no-restore
      - name: Test
        run: dotnet test ${{ github.workspace }}/Ccs.Ppg.NotificationService.sln --no-build --verbosity normal